:Author: Guillaume SARRAMEGNA
:Date: 25/05/2018
:Revision: 1.0
:License: Public Domain

= Project: Simon Says

Simple implementation of Simon Says game using Arduino and C++

== Step 1: Installation

Nothing particular, just follow step 2 and 3

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 Simon_says                => Arduino sketch folder
  ├── Simon_says.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License

This project is released under a Public Domain License.

=== Contributing

To contribute to this project please contact Guillaume SARRAMEGNA

=== BOM

Add the bill of the materials you need for this project.

|===
| ID | Part name      | Quantity
| R1 | 10k Resistor   | 4       
| R2 | 220 Resistor   | 4        
| B1 | Push button    | 4       
| L1 | Red LED        | 1       
| L2 | Green LED      | 1       
| L3 | Blue LED       | 1       
| L4 | Yellow LED     | 1        
| P1 | Piezo          | 1        
| A1 | Arduino Uno    | 1        
|===

=== Help

This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
